# Generated by Django 4.2.16 on 2024-11-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('jackets', 'Куртки'), ('jeans', 'Джинсы'), ('tshirts', 'Футболки'), ('hoodies', 'Худи'), ('shoes', 'Кроссовки и кеды')], default='tshirts', max_length=7)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image_product', models.ImageField(upload_to='images_product/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='Не указан', max_length=12)),
                ('birthday', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunclothes.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunclothes.users')),
            ],
        ),
    ]
